function single_link_wheel_leg_export(result)
%SINGLE_LINK_WHEEL_LEG_EXPORT Export LQR gains for firmware copy-paste.
%
% Author: Miya Zheng
% Created: 2026-07-30
%
% How to use:
%   result = single_link_wheel_leg_lqr();
%   Open single_link_lqr_output.txt and copy MINI_LQR_DEFAULT_K into firmware.

if nargin < 1
    result = single_link_wheel_leg_lqr();
    return;
end

K = result.KfirmwareCurrent;
outPath = fullfile(fileparts(mfilename('fullpath')), 'single_link_lqr_output.txt');
fid = fopen(outPath, 'w');
if fid < 0
    error('Cannot open output file: %s', outPath);
end

fprintf(fid, '/* Generated by single_link_wheel_leg_lqr.m, author Miya Zheng. */\n');
fprintf(fid, '/* Firmware state: pitch, pitch_rate, left_pos, left_speed, right_pos, right_speed. */\n');
fprintf(fid, '#define MINI_LQR_DEFAULT_K                  { \\\n');
for row = 1:size(K, 1)
    fprintf(fid, '    {');
    for col = 1:size(K, 2)
        fprintf(fid, '%.6ff', K(row, col));
        if col < size(K, 2)
            fprintf(fid, ', ');
        end
    end
    if row < size(K, 1)
        fprintf(fid, '}, \\\n');
    else
        fprintf(fid, '}  \\\n');
    end
end
fprintf(fid, '}\n\n');

fprintf(fid, 'Closed-loop eigenvalues:\n');
fprintf(fid, '%.9g\n', result.closedLoopEigen);
fclose(fid);
fprintf('Exported firmware gains to %s\n', outPath);
end
